{
 "title": "wis2-monitoring-demo",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MQTT-messages received per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({container_name=\"wis2-monitor-subscriber\"} |=\"INFO\" |= `New MQTT-message` [$__interval]))",
     "legendFormat": "messages received per minute"
    }
   ]
  },
  {
   "title": "Messages received by data-type",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (dt) (count_over_time( {container_name=\"wis2-monitor-subscriber\"} |= \"INFO:mqtt-subscriber:subscription=\" | pattern \"<_>subscription=<sub>, data_type=<dt>\" [10m]))",
     "legendFormat": "{{dt}}"
    }
   ]
  },
  {
   "title": "Latest messages received",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container_name=\"wis2-monitor-subscriber\"} |= `INFO:mqtt-subscriber:message` | pattern `<_>=<any>`"
    }
   ]
  }
 ]
}